global-message: La aplicaciones est√° arriba
server:
    port: 8282
endpoints.shutdown.enabled: true
spring:  
    application:
        name: configserver  
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/leosilvabustos/microservices-examples
                    searchPaths: config-files*
zuul:
    routes:
        selections:
            path: /selections/**
            serviceId: SELECTIONS
            stripPrefix: false